@echo off
setlocal EnableExtensions
cd /d "%~dp0"

set "FIREBASE_PROJECT_ID=presidential-speeches-a9f00"
set "FIREBASE_REGION=us-central1"

(
    echo @echo off
    echo rem Generated by 1-setup-config.bat
    echo set FIREBASE_PROJECT_ID=%FIREBASE_PROJECT_ID%
    echo set FIREBASE_REGION=%FIREBASE_REGION%
) > "%~dp0firebase.env.bat"

powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0\_sync-firebaserc.ps1" -ProjectId "%FIREBASE_PROJECT_ID%"

echo.
echo [OK] firebase.env.bat
echo     FIREBASE_PROJECT_ID=%FIREBASE_PROJECT_ID%
echo     FIREBASE_REGION=%FIREBASE_REGION%
echo.
echo Next: 2-install-prerequisites.bat
echo.
pause
